export const labels: Record<string, string> = {
  totals: "Gesamtwerte",
  perMatch: "Pro Match",
  coverage: "Matches mit Messwert",
  memberResults: "Mitglieder-Ergebnisse",
  member: "Mitglied",
  members: "Mitglieder",
  automatic: "Automatische Rekorde",
  allTime: "Allzeitrekorde",
  personal: "Persönliche Rekorde",
  manual: "Manuelle Rekorde",
  metric: "Kennzahl",
  value: "Wert",
  unit: "Einheit",
  observedMutualAssists: "Beobachtete gegenseitige Assists",
  stats: "Statistiken",
  events: "Beobachtete Ereignisse",
  source: "Quelle",
  timestamp: "Messzeitpunkt",
  snapshots: "Messungen",
  changes: "Veränderungen",
  FastestGoal: "Schnellstes Tor",
  StrongestBallHit: "Stärkster Ballkontakt",
  DailyWins: "Tagessiege",
  DailyWinrate: "Tages-Winrate",
  SessionMatches: "Matches pro Session",
  BestWinStreak: "Beste Siegesserie",
  GoalsPerMatch: "Tore pro Match",
  startedAt: "Beginn",
  endedAt: "Ende",
  active: "Aktiv",
  quality: "Datenqualität",
  status: "Status",
  complete: "Vollständig",
  partial: "Unvollständig",
  recovered: "Wiederhergestellt",
  verified: "Verifiziert",
  matches: "Matches",
  wins: "Siege",
  losses: "Niederlagen",
  unknown: "Unbekannt",
  winrate: "Winrate",
  Score: "Punkte",
  Goals: "Tore",
  Shots: "Schüsse",
  Assists: "Assists",
  Saves: "Paraden",
  Touches: "Ballkontakte",
  CarTouches: "Karosseriekontakte",
  Demos: "Demos",
  winStreak: "Aktuelle Siegesserie",
  lossStreak: "Aktuelle Niederlagenserie",
  bestWinStreak: "Beste Siegesserie",
  overtimeMatches: "Overtime-Matches",
  otWins: "Overtime-Siege",
  otLosses: "Overtime-Niederlagen",
  shooting: "Trefferquote",
  membersTracked: "Aktive Mitglieder",
};
